// packages/react/src/DataTable.tsx
/**
 * DataTable component: React wrapper around the vanilla table adapter.
 *
 * Mounts a table instance on render, updates when spec changes,
 * and cleans up on unmount. Supports both controlled and uncontrolled modes
 * for sort, search, and pagination state.
 */

import type { DarkMode, SortState, TableSpec, ThemeConfig } from '@opendata-ai/openchart-core';
import {
  createTable,
  type TableInstance,
  type TableMountOptions,
} from '@opendata-ai/openchart-vanilla';
import { type CSSProperties, useEffect, useRef } from 'react';
import { useVizDarkMode, useVizTheme } from './ThemeContext';

export interface DataTableProps {
  /** The table spec to render. */
  spec: TableSpec;
  /** Theme overrides. */
  theme?: ThemeConfig;
  /** Dark mode: "auto", "force", or "off". */
  darkMode?: DarkMode;
  /** Row click handler. */
  onRowClick?: (row: Record<string, unknown>) => void;
  /** Callback when sort changes. */
  onSortChange?: (sort: SortState | null) => void;
  /** Callback when search changes. */
  onSearchChange?: (query: string) => void;
  /** Callback when page changes. */
  onPageChange?: (page: number) => void;
  /** CSS class name for the wrapper div. */
  className?: string;
  /** Inline styles for the wrapper div. */
  style?: CSSProperties;
  /** Controlled sort state. */
  sort?: SortState | null;
  /** Controlled search query. */
  search?: string;
  /** Controlled page number. */
  page?: number;
}

/**
 * React component that renders a data table from a TableSpec.
 *
 * Uses the vanilla adapter internally. Supports controlled and uncontrolled
 * modes for sort, search, and pagination state.
 */
export function DataTable({
  spec,
  theme: themeProp,
  darkMode,
  onRowClick,
  onSortChange,
  onSearchChange,
  onPageChange,
  className,
  style,
  sort,
  search,
  page,
}: DataTableProps) {
  const contextTheme = useVizTheme();
  const contextDarkMode = useVizDarkMode();
  const theme = themeProp ?? contextTheme;
  const resolvedDarkMode = darkMode ?? contextDarkMode;
  const containerRef = useRef<HTMLDivElement>(null);
  const tableRef = useRef<TableInstance | null>(null);
  const prevSpecRef = useRef<TableSpec | null>(null);

  // Determine if we're in controlled mode
  const isControlled = sort !== undefined || search !== undefined || page !== undefined;

  // Effect 1: Mount/unmount. Only recreate when structural options change.
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const mountOptions: TableMountOptions = {
      theme,
      darkMode: resolvedDarkMode,
      onRowClick,
      responsive: true,
      onStateChange: (state) => {
        if (state.sort !== undefined) onSortChange?.(state.sort);
        if (state.search !== undefined) onSearchChange?.(state.search);
        if (state.page !== undefined) onPageChange?.(state.page);
      },
    };

    if (isControlled) {
      mountOptions.externalState = {
        sort: sort ?? null,
        search: search ?? '',
        page: page ?? 0,
      };
    }

    tableRef.current = createTable(container, spec, mountOptions);
    prevSpecRef.current = spec;

    return () => {
      tableRef.current?.destroy();
      tableRef.current = null;
    };
    // Only recreate on structural option changes (theme, darkMode, onRowClick).
    // Controlled state updates are handled in Effect 2.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    theme,
    resolvedDarkMode,
    onRowClick,
    isControlled,
    onPageChange,
    onSearchChange,
    onSortChange,
    page,
    search,
    sort,
    spec,
  ]);

  // Effect 2: Sync controlled state without remounting.
  useEffect(() => {
    const table = tableRef.current;
    if (!table || !isControlled) return;

    table.setState({
      sort: sort ?? null,
      search: search ?? '',
      page: page ?? 0,
    });
  }, [sort, search, page, isControlled]);

  // Effect 3: Sync spec changes via update().
  useEffect(() => {
    const table = tableRef.current;
    if (!table) return;

    // Use reference equality; users should memoize with useMemo if needed
    if (spec !== prevSpecRef.current) {
      prevSpecRef.current = spec;
      table.update(spec);
    }
  }, [spec]);

  return (
    <div
      ref={containerRef}
      className={className ? `viz-table-root ${className}` : 'viz-table-root'}
      style={style}
    />
  );
}

// packages/svelte/src/DataTable.svelte
<!--
  DataTable component: Svelte 5 wrapper around the vanilla table adapter.

  Mounts a table instance on render, updates when spec changes,
  and cleans up on unmount. Supports both controlled and uncontrolled modes
  for sort, search, and pagination state.
-->
<script lang="ts">
import type { DarkMode, SortState, TableSpec, ThemeConfig } from '@opendata-ai/openchart-core';
import {
  createTable,
  type TableInstance,
  type TableMountOptions,
} from '@opendata-ai/openchart-vanilla';
import { onMount, untrack } from 'svelte';
import { getVizDarkMode, getVizTheme } from './context.js';

let {
  spec,
  theme,
  darkMode,
  onrowclick,
  onsortchange,
  onsearchchange,
  onpagechange,
  sort,
  search,
  page,
  class: className,
  style,
}: {
  spec: TableSpec;
  theme?: ThemeConfig;
  darkMode?: DarkMode;
  onrowclick?: (row: Record<string, unknown>) => void;
  onsortchange?: (sort: SortState | null) => void;
  onsearchchange?: (query: string) => void;
  onpagechange?: (page: number) => void;
  sort?: SortState | null;
  search?: string;
  page?: number;
  class?: string;
  style?: string;
} = $props();

let containerEl: HTMLDivElement;
let instance: TableInstance | null = null;

const ctxTheme = getVizTheme();
const ctxDarkMode = getVizDarkMode();

const isControlled = $derived(sort !== undefined || search !== undefined || page !== undefined);

onMount(() => {
  return () => {
    instance?.destroy();
    instance = null;
  };
});

let prevSpec = '';

// Effect 1: Mount/recreate table on theme/darkMode changes.
$effect(() => {
  const resolvedTheme = theme ?? ctxTheme?.();
  const resolvedDarkMode = darkMode ?? ctxDarkMode?.();
  // Read spec and controlled state without tracking
  const currentSpec = untrack(() => spec);
  const currentIsControlled = untrack(() => isControlled);
  const currentSort = untrack(() => sort);
  const currentSearch = untrack(() => search);
  const currentPage = untrack(() => page);

  instance?.destroy();

  const mountOptions: TableMountOptions = {
    theme: resolvedTheme,
    darkMode: resolvedDarkMode,
    onRowClick: (row: Record<string, unknown>) => untrack(() => onrowclick)?.(row),
    responsive: true,
    onStateChange: (state) => {
      if (state.sort !== undefined) untrack(() => onsortchange)?.(state.sort);
      if (state.search !== undefined) untrack(() => onsearchchange)?.(state.search);
      if (state.page !== undefined) untrack(() => onpagechange)?.(state.page);
    },
  };

  if (currentIsControlled) {
    mountOptions.externalState = {
      sort: currentSort ?? null,
      search: currentSearch ?? '',
      page: currentPage ?? 0,
    };
  }

  instance = createTable(containerEl, currentSpec, mountOptions);
  prevSpec = JSON.stringify(currentSpec);
});

// Effect 2: Update table when spec changes (no destroy/recreate).
$effect(() => {
  const currentSpec = spec;
  if (!instance) return;

  const specString = JSON.stringify(currentSpec);
  if (specString !== prevSpec) {
    prevSpec = specString;
    instance.update(currentSpec);
  }
});

// Effect 3: Sync controlled state without remounting.
$effect(() => {
  const currentIsControlled = isControlled;
  const currentSort = sort;
  const currentSearch = search;
  const currentPage = page;
  if (!instance || !currentIsControlled) return;

  instance.setState({
    sort: currentSort ?? null,
    search: currentSearch ?? '',
    page: currentPage ?? 0,
  });
});
</script>

<div
  bind:this={containerEl}
  class={className ? `viz-table-root ${className}` : 'viz-table-root'}
  {style}
></div>
