// packages/svelte/src/Chart.svelte
<!--
  Chart component: Svelte 5 wrapper around the vanilla adapter.

  Mounts a chart instance on render, updates when spec/options change,
  and cleans up on unmount. All heavy lifting is done by the vanilla
  createChart() function.
-->
<script lang="ts">
import type {
  Annotation,
  AnnotationOffset,
  ChartSpec,
  DarkMode,
  ElementEdit,
  ElementRef,
  GraphSpec,
  LayerSpec,
  MarkEvent,
  TextAnnotation,
  ThemeConfig,
} from '@opendata-ai/openchart-core';
import { type ChartInstance, createChart, type MountOptions } from '@opendata-ai/openchart-vanilla';
import { onMount, untrack } from 'svelte';
import { getVizDarkMode, getVizTheme } from './context.js';

let {
  spec,
  theme,
  darkMode,
  onmarkclick,
  onmarkhover,
  onmarkleave,
  onlegendtoggle,
  onannotationclick,
  onannotationedit,
  onedit,
  onselect,
  ondeselect,
  ontextedit,
  ondatapointclick,
  selectedElement: selectedElementProp,
  class: className,
  style,
}: {
  spec: ChartSpec | LayerSpec | GraphSpec;
  theme?: ThemeConfig;
  darkMode?: DarkMode;
  onmarkclick?: (event: MarkEvent) => void;
  onmarkhover?: (event: MarkEvent) => void;
  onmarkleave?: () => void;
  onlegendtoggle?: (series: string, visible: boolean) => void;
  onannotationclick?: (annotation: Annotation, event: MouseEvent) => void;
  onannotationedit?: (annotation: TextAnnotation, offset: AnnotationOffset) => void;
  onedit?: (edit: ElementEdit) => void;
  onselect?: (element: ElementRef) => void;
  ondeselect?: (element: ElementRef) => void;
  ontextedit?: (element: ElementRef, oldText: string, newText: string) => void;
  ondatapointclick?: (data: Record<string, unknown>) => void;
  selectedElement?: ElementRef;
  class?: string;
  style?: string;
} = $props();

let containerEl: HTMLDivElement;
let instance: ChartInstance | null = null;

const ctxTheme = getVizTheme();
const ctxDarkMode = getVizDarkMode();

onMount(() => {
  return () => {
    instance?.destroy();
    instance = null;
  };
});

// Stable callback wrappers that read current handler props without
// creating reactive dependencies. This prevents callback prop changes
// from triggering a full chart destroy/recreate cycle.
const stableHandlers: MountOptions = {
  onMarkClick: (event: MarkEvent) => untrack(() => onmarkclick)?.(event),
  onMarkHover: (event: MarkEvent) => untrack(() => onmarkhover)?.(event),
  onMarkLeave: () => untrack(() => onmarkleave)?.(),
  onLegendToggle: (series: string, visible: boolean) =>
    untrack(() => onlegendtoggle)?.(series, visible),
  onAnnotationClick: (annotation: Annotation, event: MouseEvent) =>
    untrack(() => onannotationclick)?.(annotation, event),
  onDataPointClick: (data: Record<string, unknown>) => untrack(() => ondatapointclick)?.(data),
};

// Editing callbacks - only defined as stable wrappers, but only
// included in options when the consumer provides the prop.
const stableOnAnnotationEdit = (annotation: TextAnnotation, offset: AnnotationOffset) =>
  untrack(() => onannotationedit)?.(annotation, offset);
const stableOnEdit = (edit: ElementEdit) => untrack(() => onedit)?.(edit);
const stableOnSelect = (element: ElementRef) => untrack(() => onselect)?.(element);
const stableOnDeselect = (element: ElementRef) => untrack(() => ondeselect)?.(element);
const stableOnTextEdit = (element: ElementRef, oldText: string, newText: string) =>
  untrack(() => ontextedit)?.(element, oldText, newText);

let prevSpec = '';

// Effect 1: Mount/recreate chart on theme/darkMode changes.
// Reads spec via untrack() so spec changes don't trigger full recreate.
$effect(() => {
  const resolvedTheme = theme ?? ctxTheme?.();
  const resolvedDarkMode = darkMode ?? ctxDarkMode?.();
  // Read spec without tracking - spec changes handled in Effect 2
  const currentSpec = untrack(() => spec);

  instance?.destroy();

  const hasAnnotationEdit = untrack(() => onannotationedit) !== undefined;
  const hasEdit = untrack(() => onedit) !== undefined;
  const hasSelect = untrack(() => onselect) !== undefined;
  const hasDeselect = untrack(() => ondeselect) !== undefined;
  const hasTextEdit = untrack(() => ontextedit) !== undefined;
  const currentSelectedElement = untrack(() => selectedElementProp);

  const options: MountOptions = {
    theme: resolvedTheme,
    darkMode: resolvedDarkMode,
    responsive: true,
    ...stableHandlers,
    ...(hasAnnotationEdit ? { onAnnotationEdit: stableOnAnnotationEdit } : {}),
    ...(hasEdit ? { onEdit: stableOnEdit } : {}),
    ...(hasSelect ? { onSelect: stableOnSelect } : {}),
    ...(hasDeselect ? { onDeselect: stableOnDeselect } : {}),
    ...(hasTextEdit ? { onTextEdit: stableOnTextEdit } : {}),
    ...(currentSelectedElement ? { selectedElement: currentSelectedElement } : {}),
  };

  instance = createChart(containerEl, currentSpec, options);
  prevSpec = JSON.stringify(currentSpec);
});

// Effect 2: Update chart when spec changes (no destroy/recreate).
$effect(() => {
  const currentSpec = spec;
  if (!instance) return;

  const specString = JSON.stringify(currentSpec);
  if (specString !== prevSpec) {
    prevSpec = specString;
    instance.update(currentSpec, { selectedElement: untrack(() => selectedElementProp) });
  }
});

// Effect 3: Watch selectedElement prop changes.
$effect(() => {
  const sel = selectedElementProp;
  // Read instance without tracking to avoid coupling to Effect 1
  const inst = untrack(() => instance);
  if (!inst) return;

  if (sel) {
    inst.select(sel);
  } else {
    inst.deselect();
  }
});

// Imperative methods exposed via component exports
export function getSelectedElement(): ElementRef | null {
  return instance?.getSelectedElement() ?? null;
}

export function select(ref: ElementRef): void {
  instance?.select(ref);
}

export function deselect(): void {
  instance?.deselect();
}
</script>

<div
  bind:this={containerEl}
  class={className ? `viz-chart-root ${className}` : 'viz-chart-root'}
  {style}
></div>

// packages/react/src/Chart.tsx
/**
 * React Chart component: thin wrapper around the vanilla adapter.
 *
 * Mounts a chart instance on render, updates when spec changes,
 * and cleans up on unmount. All heavy lifting is done by the vanilla
 * createChart() function.
 */

import type {
  ChartEventHandlers,
  ChartSpec,
  DarkMode,
  ElementRef,
  GraphSpec,
  LayerSpec,
  ThemeConfig,
} from '@opendata-ai/openchart-core';
import { type ChartInstance, createChart, type MountOptions } from '@opendata-ai/openchart-vanilla';
import {
  type CSSProperties,
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
} from 'react';
import { useVizDarkMode, useVizTheme } from './ThemeContext';

export interface ChartHandle {
  /** Get the currently selected element, or null if none. */
  getSelectedElement(): ElementRef | null;
  /** Programmatically select an element. */
  select(ref: ElementRef): void;
  /** Deselect the current element. */
  deselect(): void;
  /** The underlying chart instance (null until mounted). */
  readonly instance: ChartInstance | null;
}

export interface ChartProps extends ChartEventHandlers {
  /** The visualization spec to render. */
  spec: ChartSpec | LayerSpec | GraphSpec;
  /** Theme overrides. */
  theme?: ThemeConfig;
  /** Dark mode: "auto", "force", or "off". */
  darkMode?: DarkMode;
  /** Callback when a data point is clicked. @deprecated Use onMarkClick instead. */
  onDataPointClick?: (data: Record<string, unknown>) => void;
  /** The currently selected element (controlled). */
  selectedElement?: ElementRef;
  /** CSS class name for the wrapper div. */
  className?: string;
  /** Inline styles for the wrapper div. */
  style?: CSSProperties;
}

/**
 * React component that renders a visualization from a spec.
 *
 * Uses the vanilla adapter internally. The spec is compiled and rendered
 * as SVG inside a wrapper div. Spec changes trigger re-renders via the
 * vanilla adapter's update() method.
 */
export const Chart = forwardRef<ChartHandle, ChartProps>(function Chart(
  {
    spec,
    theme: themeProp,
    darkMode,
    onDataPointClick,
    onMarkClick,
    onMarkHover,
    onMarkLeave,
    onLegendToggle,
    onAnnotationClick,
    onAnnotationEdit,
    onEdit,
    onSelect,
    onDeselect,
    onTextEdit,
    selectedElement: selectedElementProp,
    className,
    style,
  },
  ref,
) {
  const contextTheme = useVizTheme();
  const contextDarkMode = useVizDarkMode();
  const theme = themeProp ?? contextTheme;
  const resolvedDarkMode = darkMode ?? contextDarkMode;
  const containerRef = useRef<HTMLDivElement>(null);
  const chartRef = useRef<ChartInstance | null>(null);
  const specRef = useRef<string>('');

  // Store event handlers in refs so they don't trigger chart recreation.
  // Inline arrow functions create new references every render, which would
  // destroy and recreate the entire chart instance without this pattern.
  const handlersRef = useRef<{
    onDataPointClick?: ChartProps['onDataPointClick'];
    onMarkClick?: ChartProps['onMarkClick'];
    onMarkHover?: ChartProps['onMarkHover'];
    onMarkLeave?: ChartProps['onMarkLeave'];
    onLegendToggle?: ChartProps['onLegendToggle'];
    onAnnotationClick?: ChartProps['onAnnotationClick'];
    onAnnotationEdit?: ChartProps['onAnnotationEdit'];
    onEdit?: ChartProps['onEdit'];
    onSelect?: ChartProps['onSelect'];
    onDeselect?: ChartProps['onDeselect'];
    onTextEdit?: ChartProps['onTextEdit'];
  }>({});
  handlersRef.current = {
    onDataPointClick,
    onMarkClick,
    onMarkHover,
    onMarkLeave,
    onLegendToggle,
    onAnnotationClick,
    onAnnotationEdit,
    onEdit,
    onSelect,
    onDeselect,
    onTextEdit,
  };

  // Stable callback wrappers that read from refs
  const stableOnDataPointClick = useCallback(
    (data: Record<string, unknown>) => handlersRef.current.onDataPointClick?.(data),
    [],
  );
  const stableOnMarkClick = useCallback(
    (event: import('@opendata-ai/openchart-core').MarkEvent) =>
      handlersRef.current.onMarkClick?.(event),
    [],
  );
  const stableOnMarkHover = useCallback(
    (event: import('@opendata-ai/openchart-core').MarkEvent) =>
      handlersRef.current.onMarkHover?.(event),
    [],
  );
  const stableOnMarkLeave = useCallback(() => handlersRef.current.onMarkLeave?.(), []);
  const stableOnLegendToggle = useCallback(
    (series: string, visible: boolean) => handlersRef.current.onLegendToggle?.(series, visible),
    [],
  );
  const stableOnAnnotationClick = useCallback(
    (annotation: import('@opendata-ai/openchart-core').Annotation, event: MouseEvent) =>
      handlersRef.current.onAnnotationClick?.(annotation, event),
    [],
  );
  const stableOnAnnotationEdit = useCallback(
    (
      annotation: import('@opendata-ai/openchart-core').TextAnnotation,
      updatedOffset: import('@opendata-ai/openchart-core').AnnotationOffset,
    ) => handlersRef.current.onAnnotationEdit?.(annotation, updatedOffset),
    [],
  );
  const stableOnEdit = useCallback(
    (edit: import('@opendata-ai/openchart-core').ElementEdit) => handlersRef.current.onEdit?.(edit),
    [],
  );
  const stableOnSelect = useCallback(
    (element: ElementRef) => handlersRef.current.onSelect?.(element),
    [],
  );
  const stableOnDeselect = useCallback(
    (element: ElementRef) => handlersRef.current.onDeselect?.(element),
    [],
  );
  const stableOnTextEdit = useCallback(
    (element: ElementRef, oldText: string, newText: string) =>
      handlersRef.current.onTextEdit?.(element, oldText, newText),
    [],
  );

  // Expose imperative handle for ref-based control
  useImperativeHandle(
    ref,
    () => ({
      getSelectedElement() {
        return chartRef.current?.getSelectedElement() ?? null;
      },
      select(elementRef: ElementRef) {
        chartRef.current?.select(elementRef);
      },
      deselect() {
        chartRef.current?.deselect();
      },
      get instance() {
        return chartRef.current;
      },
    }),
    [],
  );

  // Mount chart and recreate when theme/darkMode change.
  // Event handlers use stable refs so they don't trigger recreation.
  // biome-ignore lint/correctness/useExhaustiveDependencies: spec intentionally excluded - spec changes handled via update() in Effect 2
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const options: MountOptions = {
      theme,
      darkMode: resolvedDarkMode,
      onDataPointClick: stableOnDataPointClick,
      onMarkClick: stableOnMarkClick,
      onMarkHover: stableOnMarkHover,
      onMarkLeave: stableOnMarkLeave,
      onLegendToggle: stableOnLegendToggle,
      onAnnotationClick: stableOnAnnotationClick,
      // Only include editing callbacks when the consumer provides them.
      // The stable wrappers are always truthy, so gating on handlersRef
      // avoids adding unstable prop references to the effect deps.
      ...(handlersRef.current.onAnnotationEdit ? { onAnnotationEdit: stableOnAnnotationEdit } : {}),
      ...(handlersRef.current.onEdit ? { onEdit: stableOnEdit } : {}),
      ...(handlersRef.current.onSelect ? { onSelect: stableOnSelect } : {}),
      ...(handlersRef.current.onDeselect ? { onDeselect: stableOnDeselect } : {}),
      ...(handlersRef.current.onTextEdit ? { onTextEdit: stableOnTextEdit } : {}),
      ...(selectedElementProp ? { selectedElement: selectedElementProp } : {}),
      responsive: true,
    };

    chartRef.current = createChart(container, spec, options);
    specRef.current = JSON.stringify(spec);

    return () => {
      chartRef.current?.destroy();
      chartRef.current = null;
    };
    // Only recreate when theme or darkMode change. Event handlers use stable refs.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    theme,
    resolvedDarkMode,
    stableOnAnnotationClick,
    stableOnDataPointClick,
    stableOnEdit,
    stableOnLegendToggle,
    stableOnMarkClick,
    stableOnMarkHover,
    stableOnMarkLeave,
    stableOnAnnotationEdit,
    stableOnSelect,
    stableOnDeselect,
    stableOnTextEdit,
  ]);

  // Update chart when spec changes
  useEffect(() => {
    const chart = chartRef.current;
    if (!chart) return;

    const specString = JSON.stringify(spec);
    if (specString !== specRef.current) {
      specRef.current = specString;
      chart.update(spec);
    }
  }, [spec]);

  // Handle selectedElement prop changes separately (like Vue/Svelte adapters)
  useEffect(() => {
    const chart = chartRef.current;
    if (!chart || !chart.select) return;

    if (selectedElementProp) {
      chart.select(selectedElementProp);
    } else if (chart.getSelectedElement?.()) {
      chart.deselect();
    }
  }, [selectedElementProp]);

  return (
    <div
      ref={containerRef}
      className={className ? `viz-chart-root ${className}` : 'viz-chart-root'}
      style={style}
    />
  );
});
