// packages/svelte/src/Graph.svelte
<!--
  Graph component: Svelte 5 wrapper around the vanilla adapter.

  Mounts a graph instance on render, updates when spec changes,
  and cleans up on unmount. All heavy lifting is done by the vanilla
  createGraph() function.

  Exposes imperative methods via component exports for programmatic
  control (search, zoom, select, fly, highlight).
-->
<script lang="ts">
import type { DarkMode, GraphSpec, ThemeConfig } from '@opendata-ai/openchart-core';
import {
  type CameraFlightOptions,
  createGraph,
  type GraphCamera,
  type GraphFlyTarget,
  type GraphHighlightTarget,
  type GraphInstance,
  type GraphLegendData,
  type GraphMountOptions,
  type GraphTooltipFormatter,
} from '@opendata-ai/openchart-vanilla';
import { onMount, untrack } from 'svelte';
import { getVizDarkMode, getVizTheme } from './context.js';

/** Tooltip prop: `false` off, `true` default, or an object with a formatter. */
type GraphTooltipProp = boolean | { formatter?: GraphTooltipFormatter };
/** Legend prop: `false` off, `true` default, or an object toggling interactivity/counts. */
type GraphLegendProp = boolean | { interactive?: boolean; counts?: boolean };

let {
  spec,
  theme,
  darkMode,
  tooltip,
  legend,
  fitOnLoad,
  initialZoom,
  onnodeclick,
  onnodedoubleclick,
  onnodehover,
  onedgehover,
  onselectionchange,
  onlegendhover,
  onlegendtoggle,
  onhighlightchange,
  oncamerachange,
  class: className,
  style,
}: {
  spec: GraphSpec;
  theme?: ThemeConfig;
  darkMode?: DarkMode;
  tooltip?: GraphTooltipProp;
  legend?: GraphLegendProp;
  fitOnLoad?: boolean;
  /** How much closer than the fit the opening camera sits: a multiplier on the fit (2 = twice as close), not an absolute zoom level. Default 1. Read once at mount; `zoomToFit()` still frames the whole graph. */
  initialZoom?: number;
  onnodeclick?: (node: Record<string, unknown>) => void;
  onnodedoubleclick?: (node: Record<string, unknown>) => void;
  onnodehover?: (node: Record<string, unknown> | null) => void;
  onedgehover?: (edge: Record<string, unknown> | null) => void;
  onselectionchange?: (nodeIds: string[]) => void;
  onlegendhover?: (entry: { field: string; value: string } | null) => void;
  onlegendtoggle?: (activeValues: string[]) => void;
  onhighlightchange?: (nodeIds: string[] | null) => void;
  oncamerachange?: (camera: GraphCamera) => void;
  class?: string;
  style?: string;
} = $props();

let containerEl: HTMLDivElement;
let instance: GraphInstance | null = null;
// First mount plays the entrance; theme/darkMode-only recreations suppress it.
let mountedOnce = false;

const ctxTheme = getVizTheme();
const ctxDarkMode = getVizDarkMode();

// Only the on/off decision gates recreation; the formatter (a function) rides
// the trampoline below so swapping it never remounts the graph.
const tooltipOn = $derived(tooltip !== false);
// Serialize the structural legend shape so a { interactive, counts } change
// recreates, but reference identity churn doesn't.
const legendKey = $derived(
  legend === false
    ? 'false'
    : legend === true || legend === undefined
      ? 'true'
      : JSON.stringify({ interactive: legend.interactive, counts: legend.counts }),
);
// 2D and 3D are different renderers, chosen once at mount, so a dimension
// change recreates the graph. A $derived over a primitive only invalidates when
// the value actually changes, so an unrelated spec edit never remounts.
const dimensions = $derived(spec.dimensions ?? 2);

// Stable tooltip formatter wrapper: always reads the LATEST formatter off the
// (untracked) prop, so a formatter can be added or swapped per-render without
// recreation and without going stale.
const stableTooltipFormatter: GraphTooltipFormatter = (item, defaults) => {
  const t = untrack(() => tooltip);
  const fn = t && typeof t === 'object' ? t.formatter : undefined;
  return fn ? fn(item, defaults) : defaults;
};

onMount(() => {
  return () => {
    instance?.destroy();
    instance = null;
  };
});

let prevSpec = '';
// Dimensions at the last mount, so a dimension-driven recreation can play its
// entrance while a theme-only one still suppresses it.
let prevDimensions = 2;

// Effect 1: Mount/recreate graph on theme/darkMode/structural option changes.
$effect(() => {
  const resolvedTheme = theme ?? ctxTheme?.();
  const resolvedDarkMode = darkMode ?? ctxDarkMode?.();
  // Read the structural tooltip/legend keys + fitOnLoad so a change to any of
  // them recreates the graph; the tooltip formatter is deliberately NOT tracked
  // (it rides the trampoline). Referencing `legendKey` here registers the
  // reactive dependency — the actual `legend` object is read untracked below.
  const on = tooltipOn;
  void legendKey;
  const fit = fitOnLoad;
  const dims = dimensions;
  const currentSpec = untrack(() => spec);

  instance?.destroy();

  const tooltipOption: GraphMountOptions['tooltip'] = on
    ? { formatter: stableTooltipFormatter }
    : false;

  const options: GraphMountOptions = {
    theme: resolvedTheme,
    darkMode: resolvedDarkMode,
    tooltip: tooltipOption,
    legend: untrack(() => legend),
    fitOnLoad: fit,
    initialZoom: untrack(() => initialZoom),
    onNodeClick: (node) => untrack(() => onnodeclick)?.(node),
    onNodeDoubleClick: (node) => untrack(() => onnodedoubleclick)?.(node),
    onNodeHover: (node) => untrack(() => onnodehover)?.(node),
    onEdgeHover: (edge) => untrack(() => onedgehover)?.(edge),
    onSelectionChange: (nodeIds) => untrack(() => onselectionchange)?.(nodeIds),
    onLegendHover: (entry) => untrack(() => onlegendhover)?.(entry),
    onLegendToggle: (activeValues) => untrack(() => onlegendtoggle)?.(activeValues),
    onHighlightChange: (nodeIds) => untrack(() => onhighlightchange)?.(nodeIds),
    onCameraChange: (camera) => untrack(() => oncamerachange)?.(camera),
    responsive: true,
    // untrack so reading the flag doesn't add a dependency; the value is set
    // after the first mount and reset only on component teardown. A dimension
    // change is exempt: the incoming renderer should play its entrance.
    suppressEntrance: untrack(() => mountedOnce) && dims === prevDimensions,
  };

  instance = createGraph(containerEl, currentSpec, options);
  prevSpec = JSON.stringify(currentSpec);
  prevDimensions = dims;
  mountedOnce = true;
});

// Effect 2: Update graph when spec changes (no destroy/recreate).
$effect(() => {
  const currentSpec = spec;
  if (!instance) return;

  const specString = JSON.stringify(currentSpec);
  if (specString !== prevSpec) {
    prevSpec = specString;
    instance.update(currentSpec);
  }
});

// Imperative methods exposed via component exports. Each forwards opts to the
// underlying instance so consumers get the full vanilla API surface.
export function search(query: string): void {
  instance?.search(query);
}

export function clearSearch(): void {
  instance?.clearSearch();
}

export function getSearchMatches(): string[] {
  return instance?.getSearchMatches() ?? [];
}

export function zoomToFit(opts?: CameraFlightOptions & { padding?: number }): void {
  instance?.zoomToFit(opts);
}

export function zoomToNode(nodeId: string, opts?: CameraFlightOptions & { scale?: number }): void {
  instance?.zoomToNode(nodeId, opts);
}

export function flyTo(target: GraphFlyTarget, opts?: CameraFlightOptions): void {
  instance?.flyTo(target, opts);
}

export function centerAt(x: number, y: number, opts?: CameraFlightOptions): void {
  instance?.centerAt(x, y, opts);
}

export function getCamera(): GraphCamera {
  return instance?.getCamera() ?? { x: 0, y: 0, k: 1 };
}

export function selectNode(nodeId: string, opts?: { fly?: boolean } & CameraFlightOptions): void {
  instance?.selectNode(nodeId, opts);
}

export function getSelectedNodes(): string[] {
  return instance?.getSelectedNodes() ?? [];
}

export function highlight(target: GraphHighlightTarget, opts?: { dimOpacity?: number }): void {
  instance?.highlight(target, opts);
}

export function clearHighlight(): void {
  instance?.clearHighlight();
}

export function getHighlight(): string[] | null {
  return instance?.getHighlight() ?? null;
}

export function getLegend(): GraphLegendData | null {
  return instance?.getLegend() ?? null;
}

export function setActiveCategories(values: string[]): void {
  instance?.setActiveCategories(values);
}

export function getActiveCategories(): string[] {
  return instance?.getActiveCategories() ?? [];
}

export function updateVisuals(nextSpec: GraphSpec): void {
  instance?.updateVisuals(nextSpec);
}
</script>

<div
  bind:this={containerEl}
  class={className ? `oc-graph-root ${className}` : 'oc-graph-root'}
  {style}
></div>

// packages/react/src/Graph.tsx
/**
 * React Graph component: thin wrapper around the vanilla adapter.
 *
 * Mounts a graph instance on render, updates when spec changes,
 * and cleans up on unmount. All heavy lifting is done by the vanilla
 * createGraph() function.
 *
 * Supports forwardRef for imperative control via useGraph() hook.
 */

import type { DarkMode, GraphSpec, ThemeConfig } from '@opendata-ai/openchart-core';
import {
  createGraph,
  type GraphCamera,
  type GraphInstance,
  type GraphMountOptions,
  type GraphTooltipFormatter,
} from '@opendata-ai/openchart-vanilla';
import {
  type CSSProperties,
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
} from 'react';
import type { GraphHandle } from './hooks/useGraph';
import { useVizDarkMode, useVizTheme } from './ThemeContext';

/** Tooltip prop: `false` off, `true` default, or an object with a formatter. */
export type GraphTooltipProp = boolean | { formatter?: GraphTooltipFormatter };
/** Legend prop: `false` off, `true` default, or an object toggling interactivity/counts. */
export type GraphLegendProp = boolean | { interactive?: boolean; counts?: boolean };

export interface GraphProps {
  /** The graph spec to render. */
  spec: GraphSpec;
  /** Theme overrides. */
  theme?: ThemeConfig;
  /** Dark mode: "auto", "force", or "off". */
  darkMode?: DarkMode;
  /** Callback when a node is clicked. */
  onNodeClick?: (node: Record<string, unknown>) => void;
  /** Callback when a node is double-clicked. */
  onNodeDoubleClick?: (node: Record<string, unknown>) => void;
  /** Callback when a node is hovered (null when hover ends). */
  onNodeHover?: (node: Record<string, unknown> | null) => void;
  /** Callback when an edge is hovered (null when hover ends). */
  onEdgeHover?: (edge: Record<string, unknown> | null) => void;
  /** Callback when selection changes. */
  onSelectionChange?: (nodeIds: string[]) => void;
  /** Fired when the user hovers a legend entry (null on leave). */
  onLegendHover?: (entry: { field: string; value: string } | null) => void;
  /** Fired when legend toggle state changes; `activeValues` is the active set (empty = all). */
  onLegendToggle?: (activeValues: string[]) => void;
  /** Fired whenever the highlight set changes (programmatic or legend), null when cleared. */
  onHighlightChange?: (nodeIds: string[] | null) => void;
  /** Camera change callback, rAF-coalesced (fires at most once per rendered frame). */
  onCameraChange?: (camera: GraphCamera) => void;
  /**
   * Show built-in tooltip on node/edge hover. Defaults to true. Pass an object
   * with a `formatter` to customize content.
   */
  tooltip?: GraphTooltipProp;
  /**
   * Show built-in legend. Defaults to true. Pass `false` if you render your own,
   * or an object to toggle interactivity/counts.
   */
  legend?: GraphLegendProp;
  /** Fit the graph to the viewport on the first tick. Default true. */
  fitOnLoad?: boolean;
  /** How much closer than the fit the opening camera sits: a multiplier on the fit (2 = twice as close), not an absolute zoom level. Default 1. Read once at mount; `zoomToFit()` still frames the whole graph. */
  initialZoom?: number;
  /** CSS class name for the wrapper div. */
  className?: string;
  /** Inline styles for the wrapper div. */
  style?: CSSProperties;
}

/** Structural (serializable) tooltip shape that participates in the mount dep key. */
function tooltipStructural(tooltip: GraphTooltipProp | undefined): boolean {
  // Only the on/off decision is structural; the formatter is a function carried
  // by the ref-trampoline, never pinned in the dep array (avoids stale closures).
  if (tooltip === false) return false;
  return true;
}

/** Structural (serializable) legend shape that participates in the mount dep key. */
function legendStructural(legend: GraphLegendProp | undefined): string {
  if (legend === false) return 'false';
  if (legend === true || legend === undefined) return 'true';
  return JSON.stringify({ interactive: legend.interactive, counts: legend.counts });
}

/**
 * React component that renders a force-directed graph from a GraphSpec.
 *
 * Uses the vanilla adapter internally. The spec is compiled and rendered
 * on a canvas inside a wrapper div. Spec changes trigger re-renders via the
 * vanilla adapter's update() method.
 *
 * Supports ref for imperative control via useGraph() hook:
 * ```tsx
 * const { ref, search, zoomToFit } = useGraph();
 * return <Graph ref={ref} spec={spec} />;
 * ```
 */
export const Graph = forwardRef<GraphHandle, GraphProps>(function Graph(
  {
    spec,
    theme: themeProp,
    darkMode,
    onNodeClick,
    onNodeDoubleClick,
    onNodeHover,
    onEdgeHover,
    onSelectionChange,
    onLegendHover,
    onLegendToggle,
    onHighlightChange,
    onCameraChange,
    tooltip,
    legend,
    fitOnLoad,
    initialZoom,
    className,
    style,
  },
  ref,
) {
  const contextTheme = useVizTheme();
  const contextDarkMode = useVizDarkMode();
  const theme = themeProp ?? contextTheme;
  const resolvedDarkMode = darkMode ?? contextDarkMode;
  const containerRef = useRef<HTMLDivElement>(null);
  const graphRef = useRef<GraphInstance | null>(null);
  const specRef = useRef<string>('');
  // Deps of the previous mount-effect run. A recreation with CHANGED deps
  // (theme/darkMode/structural-tooltip/legend — all spec-unchanged) suppresses
  // the entrance; identical deps mean a StrictMode dev replay of the same
  // mount, which must still play the entrance. A survives-cleanup boolean ref
  // can't tell those apart — it would suppress the entrance in every
  // StrictMode app.
  const prevMountDepsRef = useRef<unknown[] | null>(null);

  // Store event handlers AND function-valued options in refs so they don't
  // trigger graph recreation. Inline functions create new references every
  // render, which would either destroy+recreate the graph (if pinned in the dep
  // array) or go stale (if read once at mount). The trampoline gives us stable
  // wrappers whose bodies read the LATEST handler on every call.
  const handlersRef = useRef<{
    onNodeClick?: GraphProps['onNodeClick'];
    onNodeDoubleClick?: GraphProps['onNodeDoubleClick'];
    onNodeHover?: GraphProps['onNodeHover'];
    onEdgeHover?: GraphProps['onEdgeHover'];
    onSelectionChange?: GraphProps['onSelectionChange'];
    onLegendHover?: GraphProps['onLegendHover'];
    onLegendToggle?: GraphProps['onLegendToggle'];
    onHighlightChange?: GraphProps['onHighlightChange'];
    onCameraChange?: GraphProps['onCameraChange'];
    tooltipFormatter?: GraphTooltipFormatter;
  }>({});
  handlersRef.current = {
    onNodeClick,
    onNodeDoubleClick,
    onNodeHover,
    onEdgeHover,
    onSelectionChange,
    onLegendHover,
    onLegendToggle,
    onHighlightChange,
    onCameraChange,
    tooltipFormatter: typeof tooltip === 'object' ? tooltip.formatter : undefined,
  };

  // Stable callback wrappers that read from refs
  const stableOnNodeClick = useCallback(
    (node: Record<string, unknown>) => handlersRef.current.onNodeClick?.(node),
    [],
  );
  const stableOnNodeDoubleClick = useCallback(
    (node: Record<string, unknown>) => handlersRef.current.onNodeDoubleClick?.(node),
    [],
  );
  const stableOnNodeHover = useCallback(
    (node: Record<string, unknown> | null) => handlersRef.current.onNodeHover?.(node),
    [],
  );
  const stableOnEdgeHover = useCallback(
    (edge: Record<string, unknown> | null) => handlersRef.current.onEdgeHover?.(edge),
    [],
  );
  const stableOnSelectionChange = useCallback(
    (nodeIds: string[]) => handlersRef.current.onSelectionChange?.(nodeIds),
    [],
  );
  const stableOnLegendHover = useCallback(
    (entry: { field: string; value: string } | null) => handlersRef.current.onLegendHover?.(entry),
    [],
  );
  const stableOnLegendToggle = useCallback(
    (activeValues: string[]) => handlersRef.current.onLegendToggle?.(activeValues),
    [],
  );
  const stableOnHighlightChange = useCallback(
    (nodeIds: string[] | null) => handlersRef.current.onHighlightChange?.(nodeIds),
    [],
  );
  const stableOnCameraChange = useCallback(
    (camera: GraphCamera) => handlersRef.current.onCameraChange?.(camera),
    [],
  );
  // A stable formatter wrapper: it always calls the LATEST formatter off the ref.
  // The tooltip mount option carries this wrapper, never the raw prop function, so
  // the formatter can't go stale and can't force graph recreation.
  const stableTooltipFormatter = useCallback<GraphTooltipFormatter>(
    (item, defaults) => handlersRef.current.tooltipFormatter?.(item, defaults) ?? defaults,
    [],
  );

  // Expose imperative handle for useGraph() hook. Every method forwards opts to
  // the underlying instance so consumers get the full vanilla API surface.
  useImperativeHandle(
    ref,
    () => ({
      search(query) {
        graphRef.current?.search(query);
      },
      clearSearch() {
        graphRef.current?.clearSearch();
      },
      getSearchMatches() {
        return graphRef.current?.getSearchMatches() ?? [];
      },
      zoomToFit(opts) {
        graphRef.current?.zoomToFit(opts);
      },
      zoomToNode(nodeId, opts) {
        graphRef.current?.zoomToNode(nodeId, opts);
      },
      flyTo(target, opts) {
        graphRef.current?.flyTo(target, opts);
      },
      centerAt(x, y, opts) {
        graphRef.current?.centerAt(x, y, opts);
      },
      getCamera() {
        return graphRef.current?.getCamera() ?? { x: 0, y: 0, k: 1 };
      },
      selectNode(nodeId, opts) {
        graphRef.current?.selectNode(nodeId, opts);
      },
      getSelectedNodes() {
        return graphRef.current?.getSelectedNodes() ?? [];
      },
      highlight(target, opts) {
        graphRef.current?.highlight(target, opts);
      },
      clearHighlight() {
        graphRef.current?.clearHighlight();
      },
      getHighlight() {
        return graphRef.current?.getHighlight() ?? null;
      },
      getLegend() {
        return graphRef.current?.getLegend() ?? null;
      },
      setActiveCategories(values: string[]) {
        graphRef.current?.setActiveCategories(values);
      },
      getActiveCategories() {
        return graphRef.current?.getActiveCategories() ?? [];
      },
      updateVisuals(spec: GraphSpec) {
        graphRef.current?.updateVisuals(spec);
      },
      get instance() {
        return graphRef.current;
      },
    }),
    [],
  );

  // Structural-only parts of tooltip/legend that gate recreation. The tooltip
  // formatter (a function) is deliberately excluded — it rides the trampoline.
  const tooltipOn = tooltipStructural(tooltip);
  const legendKey = legendStructural(legend);
  // 2D and 3D are different renderers chosen once, at mount, so a dimension
  // change is a remount. It is deliberately NOT in `mountDeps`: the new
  // renderer should play its entrance rather than suppress it.
  const dimensions = spec.dimensions ?? 2;

  // Mount graph and recreate when theme/darkMode/structural options change.
  // Event handlers and the tooltip formatter use stable refs so they don't
  // trigger recreation.
  // biome-ignore lint/correctness/useExhaustiveDependencies: spec intentionally excluded - spec changes handled via update() in Effect 2
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    // Rebuild the tooltip option: keep the boolean/off decision, but always pass
    // the stable formatter wrapper when tooltips are on (so a formatter can be
    // added/changed per-render without recreating the graph).
    const tooltipOption: GraphMountOptions['tooltip'] = tooltipOn
      ? { formatter: stableTooltipFormatter }
      : false;

    // Suppress the entrance only when a PREVIOUS mount existed and a dep
    // actually changed (theme/darkMode/structural option — spec unchanged).
    // Identical deps = StrictMode's dev remount of the same graph: play it.
    const mountDeps: unknown[] = [theme, resolvedDarkMode, tooltipOn, legendKey, fitOnLoad];
    const prevDeps = prevMountDepsRef.current;
    const suppressEntrance =
      prevDeps !== null && mountDeps.some((d, i) => !Object.is(d, prevDeps[i]));

    const options: GraphMountOptions = {
      theme,
      darkMode: resolvedDarkMode,
      tooltip: tooltipOption,
      legend,
      fitOnLoad,
      // Only the opening camera reads it, so it is not a mount dep.
      initialZoom,
      onNodeClick: stableOnNodeClick,
      onNodeDoubleClick: stableOnNodeDoubleClick,
      onNodeHover: stableOnNodeHover,
      onEdgeHover: stableOnEdgeHover,
      onSelectionChange: stableOnSelectionChange,
      onLegendHover: stableOnLegendHover,
      onLegendToggle: stableOnLegendToggle,
      onHighlightChange: stableOnHighlightChange,
      onCameraChange: stableOnCameraChange,
      responsive: true,
      suppressEntrance,
    };

    graphRef.current = createGraph(container, spec, options);
    specRef.current = JSON.stringify(spec);
    prevMountDepsRef.current = mountDeps;

    return () => {
      graphRef.current?.destroy();
      graphRef.current = null;
    };
    // Only recreate when theme/darkMode/structural options change. Event handlers
    // and the tooltip formatter use stable refs.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    theme,
    resolvedDarkMode,
    tooltipOn,
    legendKey,
    fitOnLoad,
    stableOnNodeClick,
    stableOnNodeDoubleClick,
    stableOnNodeHover,
    stableOnEdgeHover,
    stableOnSelectionChange,
    stableOnLegendHover,
    stableOnLegendToggle,
    stableOnHighlightChange,
    stableOnCameraChange,
    stableTooltipFormatter,
    dimensions,
  ]);

  // Update the graph when the spec changes. `update()` diffs prev↔next itself:
  // a visual-only change (same node/edge ids + same physics) preserves positions
  // without restarting the sim; anything structural reheats with a local impulse.
  useEffect(() => {
    const graph = graphRef.current;
    if (!graph) return;

    const specString = JSON.stringify(spec);
    if (specString === specRef.current) return;
    specRef.current = specString;

    // `update` diffs internally: same node/edge ids + same physics take the
    // position-preserving path, anything structural reheats. No wrapper-side
    // heuristic needed (the old JSON-diff silently ignored physics changes).
    graph.update(spec);
  }, [spec]);

  return (
    <div
      ref={containerRef}
      className={className ? `oc-graph-root ${className}` : 'oc-graph-root'}
      style={style}
    />
  );
});
