// packages/svelte/src/Visualization.svelte
<!--
  Visualization routing component: renders Chart, DataTable, or Graph
  based on the spec type. Use this when rendering arbitrary VizSpec values.

  For event handlers, use the specific component (Chart, DataTable, Graph) directly.
-->
<script lang="ts">
import type { DarkMode, ThemeConfig, VizSpec } from '@opendata-ai/openchart-core';
import {
  isBarListSpec,
  isGeoMapSpec,
  isGraphSpec,
  isSankeySpec,
  isTableSpec,
  isTileMapSpec,
} from '@opendata-ai/openchart-core';
import BarList from './BarList.svelte';
import Chart from './Chart.svelte';
import DataTable from './DataTable.svelte';
import GeoMap from './GeoMap.svelte';
import Graph from './Graph.svelte';
import Sankey from './Sankey.svelte';
import TileMap from './TileMap.svelte';

let {
  spec,
  theme,
  darkMode,
  class: className,
  style,
}: {
  spec: VizSpec;
  theme?: ThemeConfig;
  darkMode?: DarkMode;
  class?: string;
  style?: string;
} = $props();
</script>

{#if isTableSpec(spec)}
  <DataTable {spec} {theme} {darkMode} class={className} {style} />
{:else if isGraphSpec(spec)}
  <Graph {spec} {theme} {darkMode} class={className} {style} />
{:else if isSankeySpec(spec)}
  <Sankey {spec} {theme} {darkMode} class={className} {style} />
{:else if isTileMapSpec(spec)}
  <TileMap {spec} {theme} {darkMode} class={className} {style} />
{:else if isBarListSpec(spec)}
  <BarList {spec} {theme} {darkMode} class={className} {style} />
{:else if isGeoMapSpec(spec)}
  <GeoMap {spec} {theme} {darkMode} class={className} {style} />
{:else}
  <Chart {spec} {theme} {darkMode} class={className} {style} />
{/if}

// packages/react/src/Visualization.tsx
/**
 * Visualization routing component: renders Chart, DataTable, or Graph
 * based on the spec type. Use this when rendering arbitrary VizSpec values.
 *
 * For event handlers, use the specific component (Chart, DataTable, Graph) directly.
 */

import type { DarkMode, ThemeConfig, VizSpec } from '@opendata-ai/openchart-core';
import {
  isBarListSpec,
  isGeoMapSpec,
  isGraphSpec,
  isSankeySpec,
  isTableSpec,
  isTileMapSpec,
} from '@opendata-ai/openchart-core';
import type { CSSProperties } from 'react';
import { BarList } from './BarList';
import { Chart } from './Chart';
import { DataTable } from './DataTable';
import { GeoMap } from './GeoMap';
import { Graph } from './Graph';
import { Sankey } from './Sankey';
import { TileMap } from './TileMap';

export interface VisualizationProps {
  /** The visualization spec to render. */
  spec: VizSpec;
  /** Theme overrides. */
  theme?: ThemeConfig;
  /** Dark mode: "auto", "force", or "off". */
  darkMode?: DarkMode;
  /** CSS class name for the wrapper div. */
  className?: string;
  /** Inline styles for the wrapper div. */
  style?: CSSProperties;
}

/**
 * Routes a VizSpec to the appropriate rendering component.
 *
 * Accepts any VizSpec and renders it with the correct component based on the
 * spec's type field. For event handlers, use Chart, DataTable, or Graph directly.
 */
export function Visualization({ spec, theme, darkMode, className, style }: VisualizationProps) {
  if (isTableSpec(spec)) {
    return (
      <DataTable
        spec={spec}
        theme={theme}
        darkMode={darkMode}
        className={className}
        style={style}
      />
    );
  }
  if (isGraphSpec(spec)) {
    return (
      <Graph spec={spec} theme={theme} darkMode={darkMode} className={className} style={style} />
    );
  }
  if (isSankeySpec(spec)) {
    return (
      <Sankey spec={spec} theme={theme} darkMode={darkMode} className={className} style={style} />
    );
  }
  if (isTileMapSpec(spec)) {
    return (
      <TileMap spec={spec} theme={theme} darkMode={darkMode} className={className} style={style} />
    );
  }
  if (isBarListSpec(spec)) {
    return (
      <BarList spec={spec} theme={theme} darkMode={darkMode} className={className} style={style} />
    );
  }
  if (isGeoMapSpec(spec)) {
    return (
      <GeoMap spec={spec} theme={theme} darkMode={darkMode} className={className} style={style} />
    );
  }
  return (
    <Chart spec={spec} theme={theme} darkMode={darkMode} className={className} style={style} />
  );
}
